# Generated by Django 3.0.6 on 2020-09-08 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_auto_20200905_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tweet.Comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
